### ISSUE TITLE
MY MINECRAFT KEEPS CRASHING ON START UP (I HAVE THE LATEST VERSION OF FORGE, BOTH CORE MODS, AND ALL MY MODS ARE AT THEIIR LATEST VERSION)

### ISSUE THREAD

**Issue by orco777** [BlakeDarwinXE/End-of-Days---ModPack#50]
MY MINECRAFT KEEPS CRASHING ON START UP (I HAVE THE LATEST VERSION OF FORGE, BOTH CORE MODS, AND ALL MY MODS ARE AT THEIIR LATEST VERSION).

**Comment by BlakeDarwinXE** [comment]
Can you pastbin.com the crash log for me?

**Comment by BlakeDarwinXE** [comment]
No replay to request for log in over a week.
